version: "3"

tasks:
  docker_network:
    desc: "Create server docker network."
    aliases:
      - network
    cmd: sudo docker network create phonebook_network

  docker_build:
    desc: "Build docker container for server."
    cmd: sudo docker compose -f ../build/docker-compose.yml build

  docker_run:
    desc: "Launch docker container for server."
    cmd: sudo docker compose -f ../build/docker-compose.yml up

  docker_stop:
    desc: "Stop all docker containers."
    aliases:
      - stop
    cmd: sudo docker stop $(sudo docker ps -a -q)

  docker_clean:
    desc: "Clean docker containers, images and volumes."
    cmd: sudo docker system prune -a --volumes

  clean_up:
    desc: "Clean up all folders, docker volumes, images and containers."
    dir: ../../../
    aliases:
      - clean
    cmds:
#      - sudo rm -rf grafana/
      - sudo rm -rf prometheus.yml
      - sudo rm -rf phonebook/server/build/.env
      - task: docker_clean

  copy_env:
    desc: "Prepare .env file for docker."
    internal: true
    dir: ../../../
    cmds:
      - cp .env ./phonebook/server/build/.env

  create_grafana_folder:
    desc: "Create Grafana folder for docker volume purposes."
    internal: true
    dir: ../../../
    cmds:
      - mkdir -p grafana
      - sudo chmod -R 777 grafana

  prepare_prometheus:
    desc: "Prepares Prometheus config."
    internal: true
    dir: ../../../
    cmds:
      - export $(cat .env | xargs) && envsubst < ./phonebook/server/prometheus.template.yml > prometheus.yml

  run:
    desc: "Run application and it's dependencies for production."
    cmds:
      - task: docker_stop
      - task: clean_up
      - task: copy_env
      - task: create_grafana_folder
      - task: prepare_prometheus
      - task: docker_network
      - task: docker_build
      - task: docker_run
